// LOANS ACTIONS
export const GET_LOANS = "GET_LOANS"
export const SET_SELECTED_LOAN = "SET_SELECTED_LOAN"
export const SET_LOAN_AUTOPAY_STATUS = "SET_LOAN_AUTOPAY_STATUS"

// BORROWER ACTIONS
export const GET_ME = "GET_ME"